# Generated by Django 3.1.4 on 2021-01-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_table',
            name='HOD_ID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
