# Generated by Django 3.1.4 on 2021-02-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stddata', '0002_auto_20210127_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_table',
            name='PROFILE',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='images'),
        ),
    ]
