# Generated by Django 3.1.4 on 2021-01-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='AGE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='PHONE_NUMBER',
            field=models.BigIntegerField(null=True),
        ),
    ]
